### ISSUE TITLE
Some custom settings

### ISSUE THREAD

**Issue by Kristinita** [matthewkastor/html-table-of-contents#2]
I'm sorry, I'm not a programmer in JavaScript.

_Code of my page_: https://github.com/Kristinita/Kristinita.github.io/blob/master/Gingerinas/MyTOC.html
_My page_: http://Kristinita.ru/Gingerinas/MyTOC.html
1. In my page is code `<base target="_blank">` to all links open in a new window. I want to TOC link  opened in the current window, and links to everything else in the new window. What I should do?
2. Is it possible to somehow add to the TOC markers or numbers, as in conventional marked or numbered list?
3. Is it possible to connect to the links in the TOC fonts via [Cufón](http://cufon.shoqolate.com/generate/)? 

Thanks.

**Comment by matthewkastor** [comment]
You've set the default behavior for all links to open in a new window, and the generated table of contents respects that. If you want the links to navigate around the same page, then either add `target=_self` to all of the anchors in the TOC and the anchors injected into the page, or remove the code you put in that changes the default behavior of the page. http://www.w3schools.com/jsref/prop_anchor_target.asp

And yes, you can use any fonts you'd like. There's nothing stopping you from that :D You'd implement that in other places though, it wouldn't be done by the table of contents generator. The directions for that thing you mention says you need your font files, upload them to their website, and then they'll generate some javascript for you. Then you just add the scripts to your page like they show in the directions. https://github.com/sorccu/cufon/wiki/Usage Test it out, put all the generated scripts and some html page into a folder together and then open it with your browser. Once you have the page opened, push the f12 key and look at the "network" tab. Refresh the page and you should see an entry show up that tells you whether or not the scripts were found and loaded. If they were found and loaded, then you can experiment on your page until you figure out what you want to do. To make the fonts effective on the table of contents, it looks like you'd need to edit the script where it says `Cufon.replace`, just tell it `Cufon.replace('*[id*="toc"]');` and it should change the font on anything that has an id that has "toc" in it anywhere. You could also just tell it `Cufon.replace('*');` and it should change the font on the whole page. http://www.w3schools.com/cssref/sel_attr_contain.asp You can test out things in your page by switching the developer tools to the Console tab and typing in some different `Cufon.replace` commands, just refresh the page and it will all reset back to whatever you have saved in your html file... and then you can try other codes.

Firefox's Developer Console's Console tab : 

![developer console console](https://cloud.githubusercontent.com/assets/1127586/19876370/d7832b0a-9fab-11e6-97a3-3aa107d375e8.PNG)

Firefox's Developer Console's Network tab : 

![developer console network](https://cloud.githubusercontent.com/assets/1127586/19876371/d7870680-9fab-11e6-88d1-707cac552d69.PNG)

I'm going to close this issue but you can email me if you have questions about web development. I'll show you different tools and things if you're trying to learn this stuff.

matthewkastor@gmail.com
