### ISSUE TITLE
Anchor Points Do Not Work From Outside Pages

### ISSUE THREAD

**Issue by taylornmount** [matthewkastor/html-table-of-contents#4]
I am loving this code and find it extremely useful however I am unable to link to an anchor point from page A that exists on page B. The link from page A will simply link to page B and not jump to the anchor point.

**Example:**
Page A link: https://example.com/hello-world/#anchor

Opens page B url: https://example.com/hello-world/#anchor
^ but does not scroll to #anchor

**Comment by matthewkastor** [comment]
That has nothing to do with this code.
________________________________
From: Taylor Mount ***@***.***>
Sent: Saturday, November 5, 2022 1:44:32 PM
To: matthewkastor/html-table-of-contents ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [matthewkastor/html-table-of-contents] Anchor Points Do Not Work From Outside Pages (Issue #4)


I am loving this code and find it extremely useful however I am unable to link to an anchor point from page A that exists on page B. The link from page A will simply link to page B and not jump to the anchor point.

Example:
Page A link: https://example.com/hello-world/#anchor<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fexample.com%2Fhello-world%2F%23anchor&data=05%7C01%7C%7C6eafd8b052314346feac08dabf5565c5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638032670738937295%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CMF0v6Gop4gspHAHol7kgxEv2CjCOgr7EW%2FNiQf9UE0%3D&reserved=0>

Opens page B link: https://example.com/world-world/#anchor<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fexample.com%2Fworld-world%2F%23anchor&data=05%7C01%7C%7C6eafd8b052314346feac08dabf5565c5%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638032670738937295%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yu2kf8RaxJYVQDwMbFVy3KVuKQtJGf%2FB1SiVHFuYvg4%3D&reserved=0>
^ but does not scroll to #anchor
